version = "Two"
reorder_imports = true
reorder_modules = true
max_width = 100
wrap_comments = true
combine_control_expr = true
report_todo = "Always"
use_field_init_shorthand = true
newline_style = "Unix"
remove_nested_parens = true
